*** WORK IN PROGRESS ***

Download the necessary libraries.

In [66]:
# %pip install pyreadr --quiet
# %pip install requests --quiet
import pyreadr
import requests

In [67]:
# Raw link to data
url = "https://raw.githubusercontent.com/DataSlingers/clustRviz/master/data/authors.rda"

# Download the file
with open("authors.rda", "wb") as f:
    f.write(requests.get(url).content)

# Load the .rda file
results = pyreadr.read_r("authors.rda")
results = dict(results)
# results.keys() # keys = [authors]
df = results['authors']
df = df.reset_index(drop = False).rename(columns = {'index':'BookID'})
df

,BookID,a,all,also,an,and,any,are,as,at,...,was,were,what,when,which,who,will,with,would,your
0,Austen,46.0,12.0,0.0,3.0,66.0,9.0,4.0,16.0,13.0,...,40.0,11.0,7.0,5.0,6.0,8.0,4.0,9.0,1.0,0.0
1,Austen,35.0,10.0,0.0,7.0,44.0,4.0,3.0,18.0,16.0,...,27.0,13.0,5.0,7.0,7.0,3.0,5.0,14.0,8.0,0.0
2,Austen,46.0,2.0,0.0,3.0,40.0,1.0,13.0,11.0,9.0,...,24.0,6.0,10.0,4.0,6.0,4.0,5.0,15.0,3.0,9.0
3,Austen,40.0,7.0,0.0,4.0,64.0,3.0,3.0,20.0,13.0,...,26.0,10.0,3.0,6.0,10.0,5.0,3.0,22.0,4.0,3.0
4,Austen,29.0,5.0,0.0,6.0,52.0,5.0,14.0,17.0,6.0,...,23.0,5.0,8.0,4.0,13.0,2.0,4.0,21.0,10.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
836,Shakespeare,32.0,4.0,0.0,6.0,33.0,0.0,7.0,8.0,4.0,...,0.0,1.0,13.0,2.0,3.0,3.0,11.0,17.0,5.0,10.0
837,Shakespeare,16.0,5.0,0.0,5.0,49.0,1.0,6.0,10.0,3.0,...,1.0,1.0,6.0,5.0,6.0,0.0,11.0,20.0,2.0,7.0
838,Shakespeare,22.0,15.0,0.0,3.0,48.0,0.0,9.0,10.0,2.0,...,4.0,0.0,16.0,2.0,2.0,0.0,12.0,15.0,1.0,10.0
839,Shakespeare,25.0,4.0,0.0,8.0,59.0,3.0,6.0,7.0,3.0,...,3.0,4.0,11.0,2.0,2.0,2.0,22.0,23.0,4.0,5.0
840,Shakespeare,26.0,4.0,0.0,2.0,62.0,0.0,4.0,7.0,4.0,...,5.0,0.0,13.0,2.0,5.0,3.0,11.0,19.0,0.0,3.0

In [68]:
book_id = df['BookID']
book_id.value_counts()
# 4 different books ; w/ 317 - Austen, ..., 55 - Milton.

BookID
Austen         317
London         296
Shakespeare    173
Milton          55
Name: count, dtype: int64

Data explanation - a row represents a book chapter with each column representing the word counts of key words in that chapter.  We have a BookID feature that tells us which book this corresponds to.  
For the purposes of this project we will only use this BookID column for validation of our techniques.

In [69]:
data = df.iloc[:,1:]
data

,a,all,also,an,and,any,are,as,at,be,...,was,were,what,when,which,who,will,with,would,your
0,46.0,12.0,0.0,3.0,66.0,9.0,4.0,16.0,13.0,13.0,...,40.0,11.0,7.0,5.0,6.0,8.0,4.0,9.0,1.0,0.0
1,35.0,10.0,0.0,7.0,44.0,4.0,3.0,18.0,16.0,9.0,...,27.0,13.0,5.0,7.0,7.0,3.0,5.0,14.0,8.0,0.0
2,46.0,2.0,0.0,3.0,40.0,1.0,13.0,11.0,9.0,23.0,...,24.0,6.0,10.0,4.0,6.0,4.0,5.0,15.0,3.0,9.0
3,40.0,7.0,0.0,4.0,64.0,3.0,3.0,20.0,13.0,20.0,...,26.0,10.0,3.0,6.0,10.0,5.0,3.0,22.0,4.0,3.0
4,29.0,5.0,0.0,6.0,52.0,5.0,14.0,17.0,6.0,16.0,...,23.0,5.0,8.0,4.0,13.0,2.0,4.0,21.0,10.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
836,32.0,4.0,0.0,6.0,33.0,0.0,7.0,8.0,4.0,18.0,...,0.0,1.0,13.0,2.0,3.0,3.0,11.0,17.0,5.0,10.0
837,16.0,5.0,0.0,5.0,49.0,1.0,6.0,10.0,3.0,24.0,...,1.0,1.0,6.0,5.0,6.0,0.0,11.0,20.0,2.0,7.0
838,22.0,15.0,0.0,3.0,48.0,0.0,9.0,10.0,2.0,13.0,...,4.0,0.0,16.0,2.0,2.0,0.0,12.0,15.0,1.0,10.0
839,25.0,4.0,0.0,8.0,59.0,3.0,6.0,7.0,3.0,13.0,...,3.0,4.0,11.0,2.0,2.0,2.0,22.0,23.0,4.0,5.0
840,26.0,4.0,0.0,2.0,62.0,0.0,4.0,7.0,4.0,15.0,...,5.0,0.0,13.0,2.0,5.0,3.0,11.0,19.0,0.0,3.0

### Visualization

In [70]:
#insert

### Clustering

In [71]:
#insert

### Pattern Recognition

In [72]:
#insert

### Validation

In [73]:
#insert